# GLOBAL SITE SETTINGS

# General
seo_title: ""
title: ""
company: ""
logo: "/img/content/logo.png"
description: ""
legal: "English Unlimited Brisbane Pty Ltd trading as English Unlimited | ACN: 144 733 188 | CRICOS Provider Code: 03296K"

# Contact Info
email: info@englishunlimited.qld.edu.au
phone: +61 7 3003 0088
fax: +61 7 3003 1138
address: "Level 3<br>115 Queen Street<br>Brisbane QLD 4000<br>Australia"

# Social Networks
facebook: "https://www.facebook.com/englishunlimited.com.au"

# Google Map
google_map: ""

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"